insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(101,'ineuron',400.98)
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(102,'infosys',4000.98)
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(103,'TCS',4080.98)
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(104,'JIO',1000.98)